# Site settings
title: breedR
email: facundo.munoz@orleans.inra.fr
description: > # this means to ignore newlines until "baseurl:"
  Statistical methods for forest genetic resources analysts
baseurl: /breedR
url: "http://famuvie.github.io" # the base hostname & protocol for your site
twitter_username: famuvie
github_username:  famuvie

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
 
